#!/bin/bash

if [[ $PWD != */backend ]]; then
  printf 'Please run this script from the backend directory.\n'
  exit 1
fi

bash ./setup_secrets.bash
cmd=( pip install -r requirements.txt -t lib )
[[ -d lib ]] && cmd+=( --upgrade )
gcloud app deploy app.yaml

# vim:ts=2:sw=2:expandtab
