# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PlayHvZ' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PlayHvZ
  pod 'Firebase/Core'
  pod 'GoogleSignIn'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
  target 'PlayHvZTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PlayHvZUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
